### PR TITLE
feat: replaces feather icons with material-symbols

### LINKED ISSUE #243: Replace `feather`
We are using the [feather icons](https://feathericons.com/) in various places. They are pretty, but they can only either be used by including the svg in the html source, which clutters the code, or by using the `data-feather="circle"` attribute on an element and then running `feather.replace()`, which is cumbersome, because that means we have to run `feather.replace()` everytime we change something in a DOM where an icon could be affected.

Maybe we can replace it with something that can be used without svg and javascript, directly in html? (bootstrap icons comes to mind, but maybe there are better solutions nowadays...)

### PR DESCRIPTION
**Pull request by gregorpirgie**
- removes logic for rendering feather icons
- adds link to material symbols stylesheet to base.html
- replaces all feather icons with material symbols

resolves #243

### CODE REVIEW

**Review by b1rger — APPROVED** [review]
LGTM, please squash the commits ;)

**Comment by b1rger** [comment]
> please squash the commits

(done that myself now)

**Comment by b1rger** [comment]
And thank you for your contribution! :tada:

**Comment by gregorpirgie** [comment]
@b1rger thank you! Next merge is on me.

**Pull request merged**
