### PR TITLE
fix(generic): include many-to-many relationships in list view

### PR DESCRIPTION
**Pull request by koeaw**
Include ManyToMany fields in 'additional columns' dropdown as well as in table.

Closes: #1020

### CODE REVIEW

**Comment by koeaw** [comment]
This is a minimal fix which makes `ManyToManyField`s show up in both the dropdown and the table – if un-linkified (not sure if there is a way to linkify `ManyToManyColumn`s by default).

**Review by b1rger — CHANGES_REQUESTED** [review]
The fix is not only for many-to-many relationships, but for all types of relationships. Can you change the commit message to reflect that?

Ideally the commit message would explain why you also had to change the tuple in the list comprehension to use `getattr`

**Comment by koeaw** [comment]
Can do!

**Comment by koeaw** [comment]
> The fix is not only for many-to-many relationships, but for all types of relationships. 

I've adapted the commit message, but I don't know what exactly this means because the Django source code only mentions `ManyToManyFields` in [`fields`](https://github.com/django/django/blob/aa74c4083e047473ac385753e047e075e8f04890/django/db/models/options.py#L517-L525).

I get the error for `verbose_names` I got was for `ManyToOneRel`, i.e. FK, but don't quite understand how that comes about, tbh.

**Review by b1rger — APPROVED** [review]

**Comment by b1rger** [comment]
> > The fix is not only for many-to-many relationships, but for all types of relationships.
> 
> I've adapted the commit message, but I don't know what exactly this means because the Django source code only mentions `ManyToManyFields` in [`fields`](https://github.com/django/django/blob/aa74c4083e047473ac385753e047e075e8f04890/django/db/models/options.py#L517-L525).
> 
> I get the error for `verbose_names` I got was for `ManyToOneRel`, i.e. FK, but don't quite understand how that comes about, tbh.

Ah, I thought there were other field types that are m2m, my mistake.

**Pull request merged**
