### PR TITLE
refactor: display values of fields in display view

### PR DESCRIPTION
**Pull request by koeaw**
- use _get_FIELD_display() to set field values to fix display values of choices using enumeration types (uses choices labels over values)
- simplify check for exclude_fields by incorporating it into existing function call

Closes: #506

### CODE REVIEW

**Comment by koeaw** [comment]
This basically only minimally changes what's already there, not sure if it'd be preferable to get rid of the current solution altogether.

This could also possibly be refactored further to simplify that earlier `exclude_fields` calculation.

**Review by b1rger — APPROVED** [review]
Thanks! I did not know about `_get_FIELD_display`, that makes more sense than using the form field value, which `model_to_dict` provides. I'm a little hesitant, because its a private method, but I'm ok with that for now. That refactoring makes using `model_to_dict` in fact a bit useless and it might make sense to move that whole block to a templatetag, but lets just merge it for now to fix that bug and revisit the rest later

**Comment by koeaw** [comment]
It took me a while to find out about `_get_FIELD_display()` myself while frustratingly looking for a more generic solution to `get_FOO_display()`.

I share your reservation about it being a private method, but old Django tickets I've dug up suggest there are no plans from the Django team to make functionality like this available in other ways, so... yah.

I'll note I ran into problems with _some_ fields while experimenting with getting the labels to display, but don't _quite_ remember anymore what I did/was trying to do. IIRC the problems were related to (direct or indirect?) lookups of model names, either via `_meta` or `attname` (which might be one and the same), and it happened with fields I wasn't actually aware of. Something something autofields? ... It's possible `model_to_dict` filters those out and that's part of the reason I ended up sticking with it after all (?!).

**Comment by koeaw** [comment]
Ok, I think I know now: `_get_FIELD_display()` does not work for many-to-one relationships.

When I look up all fields with `self.instance._meta.get_fields()` and try to use `_get_FIELD_display()` on them, I get "'ManyToOneRel' object has no attribute 'attname'" errors for: `uri`, `triple_set_from_subj`,  `triple_set_from_obj`.

... So I'm assuming this means we won't be able to display foreign key in our display views? Which hadn't occurred to me yet, because while we've included them in our models, we haven't actually _set_ any yet.

What's the solution to this?

**Comment by koeaw** [comment]
Maybe I should move my comments out of this PR and into the linked issue.

**Comment by koeaw** [comment]
Oups, just found this still-open PR...

**Comment by b1rger** [comment]
I'm not sure it makes sens to invest time in this - there is a WIP branch to refactor `apis_entities` to use the new `generic` app - if everything goes to plan, the whole `detail_generic.py` will be replaced

**Comment by koeaw** [comment]
> I'm not sure it makes sens to invest time in this - there is a WIP branch to refactor `apis_entities` to use the new `generic` app - if everything goes to plan, the whole `detail_generic.py` will be replaced

True, true, it doesn't make sense to pursue this particular PR further -> closing.

**Pull request closed without merging**
