### PR TITLE
Fix entity names in list view + entity_settings not getting picked up

### PR DESCRIPTION
**Pull request by koeaw**
This PR fixes (parts of) the problem reported and dicussed in #18 + another case of the recurring issue of `entity_settings` not getting applied to some model classes because class names aren't matched correctly.

Caveat: only `GenericListViewNew` in `apis_entities/views.py` was refactored, so other views may need equivalent work (depending on where/how `context` data is reused/set).

Summary of changes:
- Reverts `context['class_name']` to singular but _verbose_ name
- Introduces `context['class_name_plural']` for more flexibility in Django templates (once templates are refactored to work on a per-project basis, see acdh-oeaw/apis-rdf-devops#3)
- Improves ad-hoc pluralisation of class names which don't have `verbose_name_plural` set
- Fixes broken access of `entity_settings` configs for camel-cased class names
- Removes, simplifies redundant code, improves variables names, adapts formatting for readability
 
**Additional context**
As before, references to `settings.APIS_ENTITIES` were dropped altogether; entity settings are assumed to be set for each entity class individually in `models.py` going forward (see discussion in acdh-oeaw/apis-ontologies#9).

The use of `self` variables (or lack thereof) in this class continues to be somewhat unclear to me, but I introduced `self.entity_settings` anyway to allow for less convoluted checking for entity settings. Pointing it out in case this could have unintended effects I'm unaware of.

Lastly, the ordering in `get_queryset()` might need some further looking into because the view seems to get reused for non-entity classes as well, which do not necessarily have a `name` field objects can be ordered by.

**Related issues and PRs**
Partly solves issue:
- #18

**Checklist (Replace the space in square brackets with a lowercase x for all that apply)**
- [x] My changes don't generate new warnings or errors
- [x] My changes follow the project's code formatting rules and style guidelines
- [x] I have commented my code with Docstrings and code comments, particularly complex, unusual or hard-to-read code
- [ ] I have updated the project documentation to reflect the changes I introduce
- [ ] I have added new unit tests or updated existing ones to demonstrate my changes works

### CODE REVIEW

**Comment by koeaw** [comment]
Updated to follow black formatting rules.

**Comment by steffres** [comment]
Tested and works. Nice improvements, thank you Kay.

**Comment by koeaw** [comment]
This needs rebasing as the earlier fix for abstract classes introduced lots of (non-functional, formatting-related) changes to the file.

**Comment by koeaw** [comment]
Rebase done, merging now...

**Pull request merged**
