### PR TITLE
Gregor/refactor/entity table factory

### PR DESCRIPTION
**Pull request by gregorpirgie**
**Describe your changes**

refactor: tables.py and entities-table-factory.

Overview:

Tables.py
- refactor of tables.py file to own python module within apis_entities
- refactor of get_entities_tables factory method into factory-class.
- factory-class persists already created table-classes, instead of
   re-creating them on each request.
- inner-generic-table-class removes constraints of former implementation
- its the broadest implementation of the table
- the calling view is now responsible for customizing the instance of
   the table class that will be send to the template, instead of
   hardcoding the customization in the class itself.
- added utility class get_entities_table,
that uses the new FactoryClass, but catches all
existing calls from other modules, to not break current implementations.

GenericListViewNew in apis_entities.views.py:
- table specific code moved into own class / mixin that is now
  inherited by the GenericListViewNew
- refactored variable names
- moved seperate logic into own methods
- added docstrings: with context information that is not visible
  from the code itself.
- tried to name methods in a way that they explain what they do
- added inline comments on class vars and instance vars that are
bound to implicit logic that happens in the parent classes - these
should NOT be renamed, or things will break.
- removed as many if else statement block-series or try-except 
  blocks that where even interdependent on one another as 
  possible. The prior version was, IMO, really hard to read 
  and reason about.

**Related issues and PRs**
- #182 - implements factory refactor as an example solution for apis_entities

Resolves issue:
- #169

---> sorry, my formatter doesn't work currently and the files are not formatted correctly. <--

**Checklist (Replace the space in square brackets with a lowercase x for all that apply)**
- [x] My changes don't generate new warnings or errors
- [ ] My changes follow the project's code formatting rules and style guidelines
- [x] I have commented my code with Docstrings and code comments, particularly complex, unusual or hard-to-read code
- [ ] I have updated the project documentation to reflect the changes I introduce
- [ ] I have added new unit tests or updated existing ones to demonstrate my changes works

### CODE REVIEW

**Comment by gregorpirgie** [comment]
Styling the columns (adjusting the width) was not possible atm, this must be done in a separate PR. 

- headers are now removed for the two edit and detail columns. 
- edit and detail columns are not sortable and don't participate in sorting order
- obviously, the two columns are now also implemented, which resolves #169

**Review by b1rger — CHANGES_REQUESTED** [review]
Not going into the content right now, I'd appreciate it if the structure of the commits would be a bit more cleaned up. If you want to change something you introduced in a prior commit, please don't simply create a new commit, but fix the commit itself. Adding additional commits with bug fixes makes reviewing harder and these changes not have to land into our main history. `Bug` is not an acceptable commit title. The `Style` commit should not be a separate commit - every commit should adhere to styling conventions. In fact, every commit should run cleanly run through all the automated tests.
So: please squash you commits. Please put yourself in the shoes of your reviewers.

**Comment by b1rger** [comment]
Also, there are merge conflics. Please resolve them

**Comment by gregorpirgie** [comment]
You are totally right, I didn't notice that there where unnecessary commits, that weren't meant to be published, in the branches history. Will rework that and remember it in future commits.

**Comment by gregorpirgie** [comment]
Closing again, for new PR with squashed commits and formatted files.

**Pull request closed without merging**
