### PR TITLE
feat(history): adds tests for history plugin

### PR DESCRIPTION
**Pull request by sennierer**
currently tests for the history plugin lack an ontology for running. This is a draft PR until we added an ontology to the testing env.

### CODE REVIEW

**Review by b1rger — CHANGES_REQUESTED** [review]
We will have to move the import

**Comment by sennierer** [comment]
> We will have to move the import

is moved

**Comment by b1rger** [comment]
This should now be updated for the `sample_project` ontology

**Comment by b1rger** [comment]
ping

**Comment by sennierer** [comment]
adapted the existing tests to the sample project. presumably the check in line 11 (for the CI env variable) can be removed as the tests should now run in CI as well. However, i suggest to merge these simple tests first and lift the check for CI in another PR

**Review by b1rger — CHANGES_REQUESTED** [review]
please change the commit message to `test (history): ...` - if we cut a release, `feat` leads to a version bump

**Comment by sennierer** [comment]
good point, changed that

**Review by b1rger — APPROVED** [review]

**Pull request merged**
