### PR TITLE
birger/relations menu

### PR DESCRIPTION
**Pull request by b1rger**
- **feat(relations): add a relations_verbose_name_listview_url templatetag**
- **feat(relations): extend the base template to include relation menu items**
- **chore(sample_project): place relations before core in INSTALLED_APPS**

Closes: #1083

### CODE REVIEW

**Review by sennierer — COMMENTED** [review]
Working nicely, but i expect most projects to have 20+ relation types and in this case the menu will be quite scattered. Pushed a suggestion to add a "show more" button on >20 relations and allow for filtering/searching.

**Comment by sennierer** [comment]
btw...I dont understand the djlint changes and my local djlint doesnt find any problems

**Comment by b1rger** [comment]
> btw...I dont understand the djlint changes and my local djlint doesnt find any problems

trailing whitespaces. git diff shows you those

**Comment by sennierer** [comment]
thanks! missed that and corrected it now

**Review by sennierer — APPROVED** [review]
thats a simple, nice looking approach that will also work with high numbers of relations

**Pull request merged**
