### PR TITLE
Rh/fix/latest dependency versions

### PR DESCRIPTION
**Pull request by richardhadden**
**Describe your changes**
- Updates dependencies to latest versions:

  - Python `3.11.2`
  - Django `4.1`

  (along with required sub-dependency bumps)

  - commented some dependencies in `pyproject.toml` that don't seem necessary or used anywhere (`spacy`, `networkx`). Decide whether these are actually requirements.

- Updates to all `urls.py` files to replace `django.conf.urls.url()` with `django.urls.path()` / `django.urls.re_path` (`django.conf.urls` has been deprecated since Django 2.2, so a good idea to fix this I think).

  - TODO: @richardhadden where complex regexes for paths exist, `re_path()` was used, rather than changing the path to new syntax. It seems unlikely that regexes are actually required, and the `path` syntax, e.g. `users/<int:pk>/` can replace the less-readable regexes.

**Related pull requests**
See related pull requests in:
- https://github.com/acdh-oeaw/apis-rdf-devops/pull/42
- https://github.com/acdh-oeaw/apis-bibsonomy/pull/14
- https://github.com/acdh-oeaw/apis_highlighter/pull/4

**Checklist (Replace the space in square brackets with a lowercase x for all that apply)**
- [x] My changes don't generate new warnings or errors
- [x] My changes follow the project's code formatting rules and style guidelines
- [ ] I have commented my code with Docstrings and code comments, particularly complex, unusual or hard-to-read code
- [ ] I have updated the project documentation to reflect the changes I introduce
- [ ] I have added new unit tests or updated existing ones to demonstrate my changes works

### CODE REVIEW

**Comment by steffres** [comment]
As agreed in a JF a while ago, I had to tidy the RDF branch regarding imports and verify the functionality. This I did now with the recent commit.

**Comment by steffres** [comment]
On the overall projects requirements and updates I can not comment, as my hours for APIS are way overspent and the little remaining opens tasks for me in APIS are strictly focused on the RDF refactoring. So, I'm removing myself from the reviewer role here.

**Comment by b1rger** [comment]
> As agreed in a JF a while ago, I had to tidy the RDF branch regarding imports and verify the functionality. This I did now with the recent commit.

As you can see, this PR has a lot of conflicts that have to be resolved. It would probably be easier to cherry pick the changes and redo the PR based on the recent changes in `dev`. Adding an unrelated commit on top (that could easily be a separate PR) just makes this harder

**Comment by steffres** [comment]
You are right. I had this PR in my notes that's why I pushed it here, overlooking your suggestion. Indeed the import optimization is better to be done in a separate PR. I will do so and revert this recent commit.

**Comment by b1rger** [comment]
Closing, as this has been implemented months ago

**Pull request closed without merging**
