### PR TITLE
ci: Introduce github workflow for formatting templates

### PR DESCRIPTION
**Pull request by b1rger**

### CODE REVIEW

**Comment by koeaw** [comment]
Is there a way to set a preferred indentation with this tool? Currently, this seems to do more the opposite of what my goal is (it adds additional whitespace rather than removing it).

**Comment by b1rger** [comment]
> Is there a way to set a preferred indentation with this tool? Currently, this seems to do more the opposite of what my goal is (it adds additional whitespace rather than removing it).

Yes, `-t` - what is your preferred indentation?

**Comment by b1rger** [comment]
I've now updated the PR and set the indentation to 2 in the `pyproject.toml` - is two spaces an ok indentation?

**Comment by koeaw** [comment]
Oh no, looks like the reply I'd typed out never made it into the issue. ): Trying to recreate it from memory...

> Yes, `-t` - what is your preferred indentation?

2 spaces instead of 4, and the outermost Python block shouldn't get indented because that doesn't really do anything for readability.

The main overall concern is screen real estate because lines become very long very quickly (due to HTML nesting, which isn't a necessity from a technical POV but invaluable for readability), and neither horizontal scrolling nor the results of IDEs soft-wrapping lines are great to deal with. Reason why 2 spaces for indentation have become a thing (4 used to be the default) and why certain tags – like `<html>`, `<head>`, `<body>`  – are often not indented anymore at all, because the important stuff is what goes _inside_ the `<body>` tag.

**Comment by koeaw** [comment]
Look like we posted at the same time!

>  is two spaces an ok indentation?

Yes!

Does it have to be told separately for HTML, CSS and JS? Because I think I'm still seeing 4 spaces in some files.

**Comment by koeaw** [comment]
I'll look at the files locally, the GitHub diff doesn't necessarily make regular indentation and lining up of tags obvious.

Did you end up switching the tool? Just wondering where I should look for documentation.

**Comment by koeaw** [comment]
> Did you end up switching the tool? Just wondering where I should look for documentation.

Ok, just saw it's indeed djlint now!

**Comment by koeaw** [comment]
Related issue: acdh-oeaw/apis-rdf-devops#21

**Comment by koeaw** [comment]
> Is the linting fine the way it is for now? Should we change some configuration?

Sorry, I haven't got around to actually trying it out so far. Will try to make time this week!

**Comment by koeaw** [comment]
@b1rger I ended up installing the package to work around the merge conflicts & to take a closer look at its capabilities in general because it would be preferable if it could be used with `apis-rdf-devops` / for local development (i.e. #21).

I'm thinking it might make sense to move further discussion to the other issue.

**Comment by b1rger** [comment]
Now that we decided to use poetry for the github workflows, this is blocked by #214

**Pull request merged**
