### PR TITLE
I420-Drop utils.dl_models

### LINKED ISSUE #420: Drop `utils.dl_models`
The module is not used anywhere in the code and it relies on `keras`, which is not a dependency of apis-core-rdf

### PR DESCRIPTION
**Pull request by harsha-mangena**
**Describe your changes**
- Removed the file dl_models.py from the utils directory, as it is no longer used in the source code.

**Additional context**
- The motivation behind this change is to clean up the codebase by removing unused files, which simplifies maintenance and improves code readability.
- This decision was made after reviewing the current source code and confirming that dl_models.py is indeed not utilized in any part of the project.

**Related issues and PRs**
- This pull request addresses the issue discussed in https://github.com/acdh-oeaw/apis-core-rdf/issues/420.

Resolves issue:
- Closes #420 

Supersedes PR:
- NA

**Checklist (Replace the space in square brackets with a lowercase x for all that apply)**
- [x] My changes don't generate new warnings or errors
- [x] My changes follow the project's code formatting rules and style guidelines
- [x] I have commented my code with Docstrings and code comments, particularly complex, unusual or hard-to-read code
- [x] I have updated the project documentation to reflect the changes I introduce
- [x] I have added new unit tests or updated existing ones to demonstrate my changes works

### CODE REVIEW

**Comment by b1rger** [comment]
Hi @harsha-mangena , thanks for your contribution. We are using the [conventional commits ](https://www.conventionalcommits.org/en/v1.0.0/) standard for our commit messages, it would be great if you could fix your commit message accordingly. Please also add a `Closes: #420 ` line in the commit message.

thanks,
Birger

**Comment by harsha-mangena** [comment]
Sure, Will fix the commit, Thank for letting me know

**Comment by harsha-mangena** [comment]
@b1rger , Updated the commit message. Kindly let me know If any changes required.

**Comment by b1rger** [comment]
> @b1rger , Updated the commit message. Kindly let me know If any changes required.

The commit message is still the same, maybe you forgot to push?

**Comment by harsha-mangena** [comment]
The commit message has been updated, Kindly check.
image

**Comment by b1rger** [comment]
Thanks, I've cleaned up the commit message body (it was way to verbose) and merged the commit. Thanks for your contribution!

**Pull request closed without merging**
